export const types= {
    GET_ALLUSER : "GET_ALLUSER",
    RESET : "RESET",
    PROFILE_DATA : "PROFILE_DATA",
    DASHBOARD_COUNTS : "DASHBOARD_COUNTS",
    USER_DATA : "USER_DATA",
    GET_DASHBOARD_COUNTS: "GET_DASHBOARD_COUNTS",
    GET_PROFILE : "GET_PROFILE"
}